import { Geist, Geist_Mono } from 'next/font/google';

import { BackgroundWrapper } from '@/components/layout';
import { ThemeSelector } from '@/components/theme/ThemeSelector';
import { AuthProvider } from '@/context/AuthContext';
import { ThemeProvider } from '@/context/ThemeContext';

import type { Metadata } from 'next';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          {/* Animated background */}
          <BackgroundWrapper />

          {/* Theme selector UI */}
          <ThemeSelector />

          {/* Main content */}
          <div className="min-h-screen flex flex-col w-full">
            <div className="fixed inset-0 w-full h-full bg-gradient-to-r from-blue-400 to-purple-500 opacity-50 -z-10" />
            <div className="w-full my-10">
              <div className="w-full sm:max-w-lg mx-auto">
                <div className="flex flex-col w-full gap-4 px-3 sm:px-0">
                  <AuthProvider>{children}</AuthProvider>
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
